const JOB_STATES = {
  STARTED: "_STARTED_",
  IN_PROGRESS: "_IN_PROGRESS_",
  SAVING: "_SAVING_",
  COMPLETED: "_COMPLETED_",
  FAILED: "_FAILED_",
  NEXT: "_NEXT_",
};

const DELIVERY_NAMESPACE = "custom";
const DELIVERY_KEY = "test_delivery";

export { JOB_STATES, DELIVERY_NAMESPACE, DELIVERY_KEY };
